name: trading
channels:
  - defaults
dependencies:
  - python=3.9.18
  - joblib=1.2.0
  - matplotlib=3.5.0
  - numpy=1.22.1
  - optuna=3.3.0
  - pandas=1.5.3
  - pydantic=1.10.4
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - seaborn=0.11.2
  - ta=0.10.2
  - tqdm=4.65.0
  - python-binance=1.0.19